### PR TITLE
[Feature dictionary update] Add various missing features from mach2 repo

### PR DESCRIPTION
**Pull request by Pinguin2001**
This PR adds 86 missing features to FeatureDictionary, all of which are present in 25997

### CODE REVIEW

**Comment by thebookisclosed** [comment]
The IDs aren't ordered in their usual fashion, it should be from highest to lowest globally, plus the few high ID outliers stuck at the bottom.
I'm also quite certain that more than 86 features had to have popped up since the last dictionary update 6 months ago and I don't want to push a partial update.

**Comment by Pinguin2001** [comment]
Okay, yes, there are more which have been added.
I will create a new feature dictionary with all IDs from 25997 and sort them accordingly

**Comment by Pinguin2001** [comment]
This feature dictionary should contain all IDs from the mach2 feature repo up until Build 25997
In addition I sorted the IDs accordingly
I hope this helps!

**Comment by Pinguin2001** [comment]
image
Since the dictionary hasn't been updated in a really long time, features have been renamed, thus causing duplication problems. What should I do with them?

**Comment by thebookisclosed** [comment]
Unfortunately the latest commit is still problematic, features like USB4SettingsDomainsViewer occur multiple times with different IDs
Maintaining the list is not a fun task, if you are fine with waiting a few days more I'll make the final adjustments myself.

**Comment by thebookisclosed** [comment]
I finally powered through all the changes and a huge update/commit is now live (fef901f)

**Comment by Pinguin2001** [comment]
Great, thanks for your efforts! Finally the lists are up-to-date again

**Pull request closed without merging**
